# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = BankSystem
DESTDIR = ./x64/Release
CONFIG += release
LIBS += -L"." \
    -llibpq
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(BankSystem.pri)
